isDebug = 1
isCreateAnimation = 0
isWriteCoalQA = 1
isWriteEvents = 1
isCalculateObvs = 0
isRemoveHFQuarks = 1
isEnableMassVarify = 1
isEnableQuarkMoveOn = 0
isBalanceQuarkNumber = 1
isResampleQuarkXY = 0
isRandomRotateQuarkXY = 0
isPiesampleXY = 0
isResampleQuarkPxPy = 0
isRandomRotateQuarkPxPy = 0
isPiesamplePxPy = 0
isTurnOffRecursion = 0
isForgetZ = 1
flavourBreakTolerance = 0
eventType = kAMPT
coalescenceAlgorithm = kFromParton
r_bm = 0.5
inputFile=/Users/wangchunzheng/works/Models/cz_coal/test_data/zpc-1.root
outputFile=/Users/wangchunzheng/works/Models/cz_coal/test/dataCoalHadrons.root
obvsFile=/Users/wangchunzheng/works/Models/cz_coal/test/obvsCoalHadrons.root
