isDebug=false
isLocalDraw=false
isWriteEvents=true
isCalculateObvs=true
isRemoveHFQuarks=true
isEnableMassVarify=true
isEnableQuarkMoveOn=false
isBalanceQuarkNumber=true
eventType=kAMPT
r_bm=0.5
flavourBreakTolerance=0.001
coalescenceAlgorithm=kFromParton
inputFile=/Users/wangchunzheng/works/Models/cz_coal/test_data/zpc-1.root
outputFile=/Users/wangchunzheng/works/Models/cz_coal/test/dataCoalHadrons.root
obvsFile=/Users/wangchunzheng/works/Models/cz_coal/test/obvsCoalHadrons.root
